### PR TITLE
Fix handling of 'Required' fields for Newtonsoft

### PR DESCRIPTION
**Pull request by William-Froelich**
The existing azure-functions-openapi-extension is misalligned with Newtonsoft on which Required enumeration values are actually required and will generate a document incorrectly.

This change fixes the documentation as well as handling of the properties for generating OpenAPI documentation when using Newtonsoft JSON annotations

Fixes: https://github.com/Azure/azure-functions-openapi-extension/issues/336, https://github.com/Azure/azure-functions-openapi-extension/issues/402

### CODE REVIEW

**Comment by William-Froelich** [comment]
@microsoft-github-policy-service agree

**Comment by William-Froelich** [comment]
@justinyoo is there anything else necessary to get this change merged?

**Comment by justinyoo** [comment]
@William-Froelich I'm still trying to understand whether my interpretation of those properties `AllowNull` and `DisallowNull` is correct or not.

From the Newtonsoft.Json point of view, your change makes sense, but the OpenAPI document perspective, I'm still thinking my interpretation is more appropriate. `required` means the property MUST have value (`null` is not a value).

**Review by justinyoo — CHANGES_REQUESTED** [review]
Thanks for the update! Would you please be able to add two more tests to make sure whether your changes are OK or not?

* `RecursiveObjectTypeVisitor`
* `TypeVisitor`

**Comment by William-Froelich** [comment]
Sure. I'll add the tests as soon as i get some time this week.

**Comment by William-Froelich** [comment]
@justinyoo , I didn't see any tests for `TypeVisitor.cs` in the codebase. What test class is being used to cover that class?

**Comment by justinyoo** [comment]
> @justinyoo , I didn't see any tests for `TypeVisitor.cs` in the codebase. What test class is being used to cover that class?

Oh, never mind. It's already tested on both `ObjectTypeVisitor` and `RecursiveObjectTypeVisitor`.

**Review by justinyoo — APPROVED** [review]
@William-Froelich Thanks for the contribution! LGTM

**Pull request merged**
