### PR TITLE
GitHub Actions to generate OpenAPI document from the code

### PR DESCRIPTION
**Pull request by justinyoo**
Related to: #369 

This PR is:

* To generate an OpenAPI document within the GitHub Actions CI/CD pipeline

### CODE REVIEW

**Comment by justinyoo** [comment]
Related to #303

**Comment by justinyoo** [comment]
Related to #305

**Comment by justinyoo** [comment]
Related to #304

**Comment by justinyoo** [comment]
Related to #283

**Comment by justinyoo** [comment]
Related to #249

**Comment by justinyoo** [comment]
Related to #73

**Comment by johnnyreilly** [comment]
This is awesome! Is there guidance on how this could be repurposed if you wanted to run in Azure Pipelines or something else? Maybe a better question would be: are there docs on how to use the CLI alone to generate the swagger.json?

**Comment by johnnyreilly** [comment]
> I will provide a Power Shell script and/or bash script that you can run on any CI/CD pipeline.

That would be awesome!  We're on Azure Pipelines and would love to use this!

**Pull request merged**
