### PR TITLE
Fix: OAuth redirect url is invalid

### LINKED ISSUE #384: OAuth redirect url is invalid
**Describe the issue**
The generated redirect url from swagger.js during OAuth2 workflow in swagger ui is invalid: "http://localhost:7071http://localhost:7071/api/oauth2-redirect.html"

**To Reproduce**
- Use Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc example
- (not necessary but for better traceability): change "AuthorizationUrl" in PetStoreAuth.cs to any invalid url, so that you can see the full auth url without redirect
- Open http://localhost:7071/api/swagger/ui
- Start  oauth2 authorization
- Auth url contains "http://localhost:7071http://localhost:7071/api/oauth2-redirect.html" as redirect_uri parameter

**Expected behavior**
Auth url should contain "http://localhost:7071/api/oauth2-redirect.html" as redirect_uri parameter

**Environment (please complete the following information, if applicable):**
 - OS: Windows
 - Browser chrome
 - Version 98

### PR DESCRIPTION
**Pull request by Derich367**
Fixes #384

### CODE REVIEW

**Comment by justinyoo** [comment]
@Derich367 As your change has been made on the .js file, I don't think it's acceptable here because it can be changed at any time by the provider - Swagger UI. Instead we should look into the code replacing the placeholder of `[[SWAGGER_UI_API_PREFIX]]` here especially the line 87 and around:

https://github.com/Azure/azure-functions-openapi-extension/blob/55eec166d31ce99613061f0ba4f1f9da25869216/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs#L56-L90

**Comment by justinyoo** [comment]
@Derich367 As your change has been made on the .js file, I don't think it's acceptable here because it can be changed at any time by the provider - Swagger UI. Instead we should look into the code replacing the placeholder of `[[SWAGGER_UI_API_PREFIX]]` here especially the line 87 and around:

https://github.com/Azure/azure-functions-openapi-extension/blob/55eec166d31ce99613061f0ba4f1f9da25869216/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs#L56-L90

**Comment by Derich367** [comment]
@justinyoo Yes you are right. Sorry for the late answer.
I changed the fix, to happen inside of SwaggerUI.cs
Also added some test cases, which failed without the fix.

**Review by justinyoo — APPROVED** [review]
Thanks! It LGTM.

**Pull request merged**
