### PR TITLE
Update DocumentHelper to use GetOpenApiReferenceId for acceptor keys

### LINKED ISSUE #64: Generics not recognized well with OpenApiResponseWithBodyAttribute
When using `OpenApiResponseWithBody` on 2 different methods with a generic `MyResponse<int>` and then `MyResponse<string>`, the UI doesn't render.  Also, if only used on one method, the properties of `MyResponse` do not show in the Models section.

### PR DESCRIPTION
**Pull request by ssa3512**
Fixes #64

### CODE REVIEW

**Comment by ssa3512** [comment]
@justinyoo can you take a look at this and see if you agree this resolves the issue? I want to try and get some unit tests around this method before merging to make sure I am not inadvertently changing anything else

**Comment by justinyoo** [comment]
What a coincidence! I started looking at this issue last night! Let me have a look.

**Comment by justinyoo** [comment]
@ssa3512 That's a great catch. Thanks! It would be great if you can add some test codes around this, and it will be good to go!

**Review by justinyoo — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
